export const DISPLAY_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
export const USER_OPERATION_BEGIN = 'USER_OPERATION_BEGIN';
export const USER_OPERATION_SUCCESS = 'USER_OPERATION_SUCCESS';
export const USER_OPERATION_ERROR = 'USER_OPERATION_ERROR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';