const UserActions = {
    // user REGISTER/LOGIN constants
    USER_OPERATION_BEGIN: 'USER_OPERATION_BEGIN',
    USER_OPERATION_SUCCESS: 'USER_OPERATION_SUCCESS',
    USER_OPERATION_ERROR: 'USER_OPERATION_ERROR',

    // user LOGOUT constants
    LOGOUT_USER: 'LOGOUT_USER',

    // user UPDATE constants
    USER_UPDATE_BEGIN: 'USER_UPDATE_BEGIN',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',

    // user GET constants
    GET_USER_BEGIN: 'GET_USER_BEGIN',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
};

export default UserActions;